#!/bin/bash

# A way for mybinder.org to realize it should install the jupyter lab extension
# automatically. This file does not affect anything except when mybinder.org use
# it for this specifically.
jupyter labextension install @jupyter-widgets/jupyterlab-manager --dev-build=False --minimize=False
jupyter labextension install jupyter-matplotlib --dev-build=False --minimize=False
